### ISSUE TITLE
Unable to register PoP with Keystone v3

### ISSUE THREAD

**Issue by maaznkazi** [openbaton/openstack4j-plugin#54]
Hello Team,

Am trying to register a PoP with Keystone v3, but am getting error "Unauthorized" under VIM driver plugin.

Am using the latest version of OpenBaton

Below are error logs :
[pool-3-thread-1] ERROR org.openbaton.drivers.openstack4j.OpenStack4JDriver - Unauthorized
org.openbaton.exceptions.VimDriverException: Unauthorized
        at org.openbaton.drivers.openstack4j.OpenStack4JDriver.authenticate(OpenStack4JDriver.java:183)

On the keystone side am getting below error:

Authorization failed. The request you have made requires authentication. from x.x.x.x.

Please suggest how to deal with this error.

**Comment by gc4rella** [comment]
Please refer to this doc: http://openbaton.github.io/documentation/pop-openstack/ 

Please close the issue when solved.

**Comment by maaznkazi** [comment]
Not an issue.. I was trying with projectID instead of tenantID
