### ISSUE TITLE
External-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist

### ISSUE THREAD

**Issue by Polpetta** [openbaton/openstack4j-plugin#72]
When spinning up your driver using Docker, I get into the log:
`[main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist`

Checking the project's `plugin.conf.properties` file, there is the following line:
https://github.com/openbaton/openstack4j-plugin/blob/7097220493c47617db9913e04bb53a95d2b1b53b/src/main/resources/plugin.conf.properties#L21

but in the gradle build this file never gets generated nor copied in that directory.

**Comment by mpauls** [comment]
This is just an optional option - you can provide it or not. If this file doesn't exist, it will use the default one in the jar archive. Additionally, you can pass configuration parameters via environment variables when running the container itself.
